name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
permissions:
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Format check
      run: cargo fmt -- --check

    - name: Lint check
      run: cargo clippy -- -D warnings

    - name: Build release
      run: cargo build --release

    - name: Upload binary
      uses: actions/upload-artifact@v3
      with:
        name: spotify-tui
        path: target/release/spt
